package env

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type EnvEntry struct {
	Name  string
	Value string
}

func UpdateEnv(envDir string, outputDir string) error {
	if envDir == "" {
		envDir = "/etc/env.d"
	}
	if outputDir == "" {
		outputDir = "/etc"
	}

	entries, err := ReadEnvDir(envDir)
	if err != nil {
		return fmt.Errorf("env-update: read %s: %w", envDir, err)
	}

	merged := mergeEnvEntries(entries)

	if err := writeProfileEnv(filepath.Join(outputDir, "profile.env"), merged); err != nil {
		return fmt.Errorf("env-update: write profile.env: %w", err)
	}

	if err := writeCshEnv(filepath.Join(outputDir, "csh.env"), merged); err != nil {
		return fmt.Errorf("env-update: write csh.env: %w", err)
	}

	return nil
}

func ReadEnvDir(envDir string) ([]EnvEntry, error) {
	entries, err := os.ReadDir(envDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var sorted []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, ".") {
			continue
		}
		sorted = append(sorted, name)
	}
	sort.Strings(sorted)

	var result []EnvEntry
	for _, name := range sorted {
		path := filepath.Join(envDir, name)
		fileEntries, err := parseEnvFile(path)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", name, err)
		}
		result = append(result, fileEntries...)
	}

	return result, nil
}

func parseEnvFile(path string) ([]EnvEntry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	lines := strings.Split(string(data), "\n")
	var entries []EnvEntry

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}

		name := strings.TrimSpace(line[:idx])
		value := line[idx+1:]
		value = unquoteSh(value)

		if name == "" {
			continue
		}

		entries = append(entries, EnvEntry{Name: name, Value: value})
	}

	return entries, nil
}

func mergeEnvEntries(entries []EnvEntry) []EnvEntry {
	seen := make(map[string]int)

	for _, e := range entries {
		name := e.Name
		switch name {
		case "PATH", "MANPATH", "INFOPATH", "LDPATH", "ROOTPATH":
			seen[name]++
			continue
		default:
			seen[name] = 1
		}
	}

	order := make([]string, 0, len(seen))
	for _, e := range entries {
		name := e.Name
		if _, exists := seen[name]; !exists {
			continue
		}
		delete(seen, name)
		order = append(order, name)
	}

	dedupSpecial := map[string]bool{
		"PATH":     true,
		"MANPATH":  true,
		"INFOPATH": true,
		"LDPATH":   true,
		"ROOTPATH": true,
	}

	result := make([]EnvEntry, 0, len(order))
	for _, name := range order {
		if dedupSpecial[name] {
			var parts []string
			partSet := map[string]bool{}
			for _, e := range entries {
				if e.Name != name {
					continue
				}
				for _, p := range splitColon(e.Value) {
					p = strings.TrimSpace(p)
					if p == "" || partSet[p] {
						continue
					}
					partSet[p] = true
					parts = append(parts, p)
				}
			}
			result = append(result, EnvEntry{Name: name, Value: strings.Join(parts, ":")})
		} else {
			last := ""
			for _, e := range entries {
				if e.Name == name {
					last = e.Value
				}
			}
			result = append(result, EnvEntry{Name: name, Value: last})
		}
	}

	return result
}

func splitColon(s string) []string {
	s = unquoteSh(s)
	return strings.Split(s, ":")
}

func writeProfileEnv(path string, entries []EnvEntry) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var buf strings.Builder
	buf.WriteString("# Generated by arise env-update. Do not edit.\n")

	for _, e := range entries {
		val := e.Value
		val = quoteBash(val)

		switch e.Name {
		case "PATH":
			buf.WriteString(fmt.Sprintf("export PATH=%s\n", val))
		case "ROOTPATH":
			buf.WriteString(fmt.Sprintf("export ROOTPATH=%s\n", val))
		case "MANPATH":
			buf.WriteString(fmt.Sprintf("export MANPATH=%s\n", val))
		case "INFOPATH":
			buf.WriteString(fmt.Sprintf("export INFOPATH=%s\n", val))
		case "LDPATH":
			buf.WriteString(fmt.Sprintf("export LDPATH=%s\n", val))
		default:
			buf.WriteString(fmt.Sprintf("export %s=%s\n", e.Name, val))
		}
	}

	return os.WriteFile(path, []byte(buf.String()), 0644)
}

func writeCshEnv(path string, entries []EnvEntry) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var buf strings.Builder
	buf.WriteString("# Generated by arise env-update. Do not edit.\n")

	for _, e := range entries {
		val := quoteCsh(e.Value)

		switch e.Name {
		case "PATH":
			buf.WriteString(fmt.Sprintf("setenv PATH %s\n", val))
		case "ROOTPATH":
			buf.WriteString(fmt.Sprintf("setenv ROOTPATH %s\n", val))
		case "MANPATH":
			buf.WriteString(fmt.Sprintf("setenv MANPATH %s\n", val))
		case "INFOPATH":
			buf.WriteString(fmt.Sprintf("setenv INFOPATH %s\n", val))
		case "LDPATH":
			buf.WriteString(fmt.Sprintf("setenv LDPATH %s\n", val))
		default:
			buf.WriteString(fmt.Sprintf("setenv %s %s\n", e.Name, val))
		}
	}

	return os.WriteFile(path, []byte(buf.String()), 0644)
}

func quoteBash(s string) string {
	if !strings.ContainsAny(s, "\"' \t$`\\") {
		return s
	}
	escaped := strings.ReplaceAll(s, `"`, `\"`)
	return `"` + escaped + `"`
}

func quoteCsh(s string) string {
	if !strings.ContainsAny(s, "\"' \t$`\\") {
		return s
	}
	escaped := strings.ReplaceAll(s, `"`, `\"`)
	return `"` + escaped + `"`
}

func unquoteSh(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') ||
			(s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func RunLdConfig(rootDir string) error {
	return fmt.Errorf("ldconfig: not yet implemented; run /sbin/ldconfig manually or via system package")
}
