package env

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// UpdateResult describes the externally useful work performed by UpdateRoot.
type UpdateResult struct {
	EnvironmentFiles int
	LinkerPaths      []string
	LdconfigRan      bool
}

// UpdateRoot implements the Linux portion of Portage env_update for ROOT.
// ldconfigOverride is intended for cross-toolchains and tests; when empty the
// executable below ROOT/sbin is used, exactly as Portage does.
func UpdateRoot(root, ldconfigOverride string, runLinkerCache bool) (UpdateResult, error) {
	root = filepath.Clean(root)
	if !filepath.IsAbs(root) {
		return UpdateResult{}, fmt.Errorf("env-update: ROOT must be absolute: %s", root)
	}
	envDir := filepath.Join(root, "etc", "env.d")
	if err := os.MkdirAll(envDir, 0o755); err != nil {
		return UpdateResult{}, fmt.Errorf("env-update: create %s: %w", envDir, err)
	}
	entries, err := os.ReadDir(envDir)
	if err != nil {
		return UpdateResult{}, fmt.Errorf("env-update: read %s: %w", envDir, err)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	configs := make([]map[string]string, 0, len(entries))
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || len(name) < 3 || name[0] < '0' || name[0] > '9' || name[1] < '0' || name[1] > '9' || strings.HasPrefix(name, ".") || strings.HasSuffix(name, "~") || strings.HasSuffix(name, ".bak") {
			continue
		}
		parsed, parseErr := parseEnvConfig(filepath.Join(envDir, name))
		if parseErr != nil {
			return UpdateResult{}, parseErr
		}
		configs = append(configs, parsed)
	}

	spaceSeparated := stringSet("CONFIG_PROTECT", "CONFIG_PROTECT_MASK")
	colonSeparated := stringSet("ADA_INCLUDE_PATH", "ADA_OBJECTS_PATH", "CLASSPATH", "INFODIR", "INFOPATH", "KDEDIRS", "LDPATH", "MANPATH", "PATH", "PKG_CONFIG_PATH", "PRELINK_PATH", "PRELINK_PATH_MASK", "PYTHONPATH", "ROOTPATH")
	for _, config := range configs {
		for _, name := range strings.Fields(config["SPACE_SEPARATED"]) {
			spaceSeparated[name] = true
		}
		for _, name := range strings.Fields(config["COLON_SEPARATED"]) {
			colonSeparated[name] = true
		}
		delete(config, "SPACE_SEPARATED")
		delete(config, "COLON_SEPARATED")
	}

	merged := make(map[string]string)
	for name := range spaceSeparated {
		values := collectSeparated(configs, name, " ")
		if len(values) != 0 {
			merged[name] = strings.Join(values, " ")
		}
	}
	for name := range colonSeparated {
		values := collectSeparated(configs, name, ":")
		if len(values) != 0 {
			merged[name] = strings.Join(values, ":")
		}
	}
	for _, config := range configs {
		for name, value := range config {
			if !spaceSeparated[name] && !colonSeparated[name] {
				merged[name] = value
			}
		}
	}

	linkerPaths := strings.Split(merged["LDPATH"], ":")
	if merged["LDPATH"] == "" {
		linkerPaths = nil
	}
	ldConf := "# ld.so.conf autogenerated by env-update; make all changes to\n# contents of /etc/env.d directory.\n"
	for _, path := range linkerPaths {
		ldConf += path + "\n"
	}
	if err := writeAtomic(filepath.Join(root, "etc", "ld.so.conf"), []byte(ldConf), 0o644); err != nil {
		return UpdateResult{}, fmt.Errorf("env-update: write ld.so.conf: %w", err)
	}
	delete(merged, "LDPATH")
	keys := make([]string, 0, len(merged))
	for name := range merged {
		keys = append(keys, name)
	}
	sort.Strings(keys)
	notice := "# THIS FILE IS AUTOMATICALLY GENERATED BY env-update.\n# DO NOT EDIT THIS FILE."
	profile := notice + " CHANGES TO STARTUP PROFILES\n# GO INTO /etc/profile NOT /etc/profile.env\n\n"
	csh := notice + " CHANGES TO STARTUP PROFILES\n# GO INTO /etc/csh.cshrc NOT /etc/csh.env\n\n"
	systemd := notice + "\n\n"
	for _, name := range keys {
		value := merged[name]
		profile += "export " + name + "=" + shellSingleQuote(value) + "\n"
		csh += "setenv " + name + " " + shellSingleQuote(value) + "\n"
		if value != "" {
			systemd += name + "=" + value + "\n"
		}
	}
	for path, content := range map[string]string{
		filepath.Join(root, "etc", "profile.env"):                         profile,
		filepath.Join(root, "etc", "csh.env"):                             csh,
		filepath.Join(root, "etc", "environment.d", "10-gentoo-env.conf"): systemd,
	} {
		if err := writeAtomic(path, []byte(content), 0o644); err != nil {
			return UpdateResult{}, fmt.Errorf("env-update: write %s: %w", path, err)
		}
	}
	result := UpdateResult{EnvironmentFiles: len(configs), LinkerPaths: append([]string(nil), linkerPaths...)}
	if !runLinkerCache {
		return result, nil
	}
	ldconfig := ldconfigOverride
	if ldconfig == "" {
		ldconfig = filepath.Join(root, "sbin", "ldconfig")
	}
	info, statErr := os.Stat(ldconfig)
	if os.IsNotExist(statErr) {
		return result, nil
	}
	if statErr != nil || !info.Mode().IsRegular() || info.Mode().Perm()&0o111 == 0 {
		return result, fmt.Errorf("env-update: unusable ldconfig %s", ldconfig)
	}
	if runErr := runLdconfig(root, ldconfig); runErr != nil {
		return result, runErr
	}
	result.LdconfigRan = true
	return result, nil
}

func runLdconfig(root, executable string) error {
	command := exec.Command(executable, "-X", "-r", root)
	command.Dir = "/"
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("env-update: ldconfig -X -r %s: %w: %s", root, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func parseEnvConfig(path string) (map[string]string, error) {
	entries, err := parseEnvFile(path)
	if err != nil {
		return nil, fmt.Errorf("env-update: parse %s: %w", path, err)
	}
	result := make(map[string]string)
	for _, entry := range entries {
		result[entry.Name] = entry.Value
	}
	return result, nil
}

func stringSet(values ...string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}

func collectSeparated(configs []map[string]string, name, separator string) []string {
	var result []string
	seen := make(map[string]bool)
	for _, config := range configs {
		value, exists := config[name]
		if !exists {
			continue
		}
		delete(config, name)
		parts := strings.Fields(value)
		if separator == ":" {
			parts = strings.Split(value, ":")
		}
		for _, part := range parts {
			if part != "" && !seen[part] {
				seen[part] = true
				result = append(result, part)
			}
		}
	}
	return result
}

func shellSingleQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func writeAtomic(path string, content []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".arise-env-update-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return err
	}
	directory, err := os.Open(filepath.Dir(path))
	if err != nil {
		return err
	}
	defer directory.Close()
	return directory.Sync()
}
